### ISSUE TITLE
Update Azure demonstrations 

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#126]
In  https://github.com/Senzing/kubernetes-demo/issues/118, the following demonstrations were updated for "Senzing baked-in" containers:

- https://github.com/Senzing/kubernetes-demo/tree/main/docs/helm-rabbitmq-postgresql
- https://github.com/Senzing/kubernetes-demo/tree/main/docs/helm-rabbitmq-mysql
- https://github.com/Senzing/kubernetes-demo/tree/main/docs/helm-kafka-postgresql
- https://github.com/Senzing/kubernetes-demo/tree/main/docs/helm-rabbitmq-postgresql-airgapped

This issue is to update:

- https://github.com/Senzing/kubernetes-demo/tree/main/docs/azure-helm-message-bus-mssql
- https://github.com/Senzing/kubernetes-demo/tree/main/docs/azure-helm-rabbitmq-postgresql

**Comment by docktermj** [comment]
Blocked by https://github.com/Senzing/init-mssql/issues/3

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
