### ISSUE TITLE
Update Db2 demonstration

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#127]
In  https://github.com/Senzing/kubernetes-demo/issues/118, the following demonstrations were updated for "Senzing baked-in" containers:

- https://github.com/Senzing/kubernetes-demo/tree/main/docs/helm-rabbitmq-postgresql
- https://github.com/Senzing/kubernetes-demo/tree/main/docs/helm-rabbitmq-mysql
- https://github.com/Senzing/kubernetes-demo/tree/main/docs/helm-kafka-postgresql
- https://github.com/Senzing/kubernetes-demo/tree/main/docs/helm-rabbitmq-postgresql-airgapped

This issue is to update:

- https://github.com/Senzing/kubernetes-demo/tree/main/docs/helm-rabbitmq-db2

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
