### ISSUE TITLE
Add "how to install license" to the instructions.

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#40]
**Is your feature request related to a problem? Please describe.**
The current instructions do not show how to optionally add a license.

**Describe the solution you'd like**
Add optional instructions for applying a Senzing license

**Comment by docktermj** [comment]
Similar to the instructions documented for the OpenShift demo at 
https://github.com/Senzing/ibm-openshift-guide/blob/master/docs/helm-rabbitmq-db2/README.md#install-senzing-license

The "oc" command in OpenShift is very similar to the "kubectl" command in Kubernetes.   So where you see "oc cp ...."  use "kubectl cp ..."

Also note that if using the debug container the path is `/etc/opt/senzing/g2.lic` not `/opt/senzing/senzing-etc/g2.lic`.   That refers to the use of the "subPath" mount for `senzing-etc`.  So be a little careful in crafting the instructions.

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
