### ISSUE TITLE
Add "how to add datasources" to the instructions

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#41]
**Is your feature request related to a problem? Please describe.**
The current instructions do not show how to optionally add datasources.

**Describe the solution you'd like**
Add optional instructions for adding datasources.

**Comment by docktermj** [comment]
### Manual method:

1. "exec" to the debug container (i.e. the Senzing-debug Helm Chart)
2. cd /opt/senzing/g2/python
3. Run "./G2ConfigTool.py -c /etc/opt/senzing/G2Module.ini"
    > addDataSource {"dataSource": "<dataSource_name>"}
    > save
    > quit

(Note: this method currently has a bug when trying to store commands to a "history" file)

To fix the issue, make a file with one line per command, Example:

my-senzing-datasources.txt:
```
addDataSource {"dataSource": "<dataSource_name>"}
addDataSource {"dataSource": "<dataSource_name_2>"}
save
quit
```
Add as many "addDataSource { ... }" lines as you want.   Then run the command in this fashion:

./G2ConfigTool.py -c /etc/opt/senzing/G2Module.ini -f /path/to/my-senzing-datasources.txt

The avoids the use of the "personal history file"   (.g2configtool_history)

**Comment by docktermj** [comment]
### Micro-service method:

In the OpenShift demo at https://github.com/Senzing/ibm-openshift-guide/blob/master/docs/helm-rabbitmq-db2/README.md#install-senzing-configurator-helm-chart there is a "configurator" micro service that allows you to define data sources via HTTP request.  See https://github.com/Senzing/configurator for more details on the HTTP API.

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
