### ISSUE TITLE
Re-introduce Db2

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#68]
In the past, Db2 was supported as a database:

1. https://github.com/Senzing/kubernetes-demo/tree/master/docs/helm-kafka-db2
2. https://github.com/Senzing/kubernetes-demo/tree/master/docs/helm-rabbitmq-db2

However, with an update of Db2, the use of Helm Charts stopped working. This issue is to re-introduce Db2 as a database option.

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
