### ISSUE TITLE
Documentation doesn't mention having to perform a helm init

### ISSUE THREAD

**Issue by antaenc** [senzing-garage/kubernetes-demo#74]
https://github.com/Senzing/kubernetes-demo/tree/issue-69.dockter.2/docs/helm-rabbitmq-postgresql#add-helm-repositories

First helm command fails with:

> Error: Couldn't load repositories file (/home/ant/.helm/repository/repositories.yaml).
> You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)

First run through on clean machine, needed to issue helm init command.

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
