### ISSUE TITLE
Documentation - needed to add -- for the name on helm install

### ISSUE THREAD

**Issue by antaenc** [senzing-garage/kubernetes-demo#75]
At https://github.com/Senzing/kubernetes-demo/tree/issue-69.dockter.2/docs/helm-rabbitmq-postgresql#non-root-container-method received error running helm install:

```
--> helm install \
>   name ${DEMO_PREFIX}-senzing-base \
>   senzing/senzing-base \
>   --namespace ${DEMO_NAMESPACE} \
>   --values ${GIT_REPOSITORY_DIR}/helm-values/senzing-base.yaml
Error: This command needs 1 argument: chart name
```
 Needed to add -- to name

**Comment by antaenc** [comment]
Also in these locations, name was specified had to add --name

https://github.com/Senzing/kubernetes-demo/tree/issue-69.dockter.2/docs/helm-rabbitmq-postgresql#install-senzing-console-helm-chart

```
helm install \
  ${DEMO_PREFIX}-senzing-console \
  senzing/senzing-console \
  --namespace ${DEMO_NAMESPACE} \
  --values ${GIT_REPOSITORY_DIR}/helm-values/senzing-console-postgresql.yaml
```


https://github.com/Senzing/kubernetes-demo/tree/issue-69.dockter.2/docs/helm-rabbitmq-postgresql#install-postgresql-helm-chart

```
helm install \
  ${DEMO_PREFIX}-postgresql \
  bitnami/postgresql \
  --namespace ${DEMO_NAMESPACE} \
  --values ${HELM_VALUES_DIR}/postgresql.yaml \
  --version v6.5.7

```

And subsequent helm install commands after this one.

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
