### ISSUE TITLE
Add Redoer queueing

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#78]
The current set of instructions at https://github.com/Senzing/kubernetes-demo/tree/master/docs/azure-helm-message-bus-mssql do not show how to define a queue for redoing, nor setting up the "redoer-producer" and "redoer-loaders" (which autoscale).  

Instructions need to be added.

See https://github.com/Senzing/kubernetes-demo/issues/69

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
