### ISSUE TITLE
Add Security

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#79]
The current set of instructions at https://github.com/Senzing/kubernetes-demo/tree/master/docs/azure-helm-message-bus-mssql do not show security similar to AWS's Cognito.

The azure-helm-message-bus-mssql instructions need to add a layer of security.  This will be done in 2 layers:

1. The kubernetes layer
2. The Azure layer

See https://github.com/Senzing/kubernetes-demo/issues/69

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
