### ISSUE TITLE
Support a custom license

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#80]
The current set of instructions at https://github.com/Senzing/kubernetes-demo/tree/master/docs/azure-helm-message-bus-mssql do not show how to add a custom `g2.lic` (or the base64 equivalent).

Instructions need to be added.

See https://github.com/Senzing/kubernetes-demo/issues/69

**Comment by docktermj** [comment]
This would also satisfy #40

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
