### ISSUE TITLE
Support sharded (3) databases

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#81]
The current set of instructions at https://github.com/Senzing/kubernetes-demo/tree/master/docs/azure-helm-message-bus-mssql only show how to deploy to a single Azure SQL Database.

Instructions need to be added to show how to deploy 3 databases for Senzing "sharding".

See https://github.com/Senzing/kubernetes-demo/issues/69

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
