### ISSUE TITLE
Route through single host with URI pathing using SSL/TLS

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#82]
The current set of instructions at https://github.com/Senzing/kubernetes-demo/tree/master/docs/azure-helm-message-bus-mssql only supports "port-forwarding" to view the API service and the Entity Search Web App.

The instruction need to show how to set up  NodePort, LoadBalancer, ClusterIP and/or something else to aggregate the service under one hostname.

The service needs to be accessible via secure connection (SSL/TLS).

See https://github.com/Senzing/kubernetes-demo/issues/69

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
