### ISSUE TITLE
Improve SwaggerUI

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#88]
The current set of instructions at https://github.com/Senzing/kubernetes-demo/tree/master/docs/azure-helm-message-bus-mssql does create a SwaggerUI that can reach the Senzing API Server due to CORS restrictions.

Instructions need to be added to show how to fix this.  (It may take an Nginx proxy to pull this off.)

See https://github.com/Senzing/kubernetes-demo/issues/69

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
