### ISSUE TITLE
Add Jupyter Notebooks

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#90]
The current set of instructions at https://github.com/Senzing/kubernetes-demo/tree/master/docs/azure-helm-message-bus-mssql does create the Jupyter Notebooks container/pod.

Instructions need to be added to show how to deploy.

See https://github.com/Senzing/kubernetes-demo/issues/69

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
