### ISSUE TITLE
Add Autoscaling of redoer-loader

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#91]
The current set of instructions at https://github.com/Senzing/kubernetes-demo/tree/master/docs/azure-helm-message-bus-mssql do not show how to define autoscaling for redoer-loader.  

Instructions need to be added.

See https://github.com/Senzing/kubernetes-demo/issues/69

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
