### ISSUE TITLE
Use runix/pgadmin4, not senzing/phppgadmin

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/kubernetes-demo#94]
Use the `runix/pgadmin4` Helm Chart which uses the `dpage/pgadmin4` Docker image.

### Background

Bitnami [bitnami/phppgadmin](https://hub.docker.com/r/bitnami/phppgadmin) docker image has been deprecated.
And a Bitnami Helm chart for phppgadmin no longer exists (https://github.com/bitnami/charts/tree/master/bitnami).

**Comment by kernelsam** [comment]
Closing as this repo is being archived.
